/*
 * notifier
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.3.0
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * GetTelegramChatIdBody
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-08-24T13:14:10.044526Z[Etc/UTC]")
public class GetTelegramChatIdBody {
  public static final String SERIALIZED_NAME_TELEGRAM_USERNAME = "telegram_username";
  @SerializedName(SERIALIZED_NAME_TELEGRAM_USERNAME)
  private String telegramUsername;

  public GetTelegramChatIdBody() { 
  }

  public GetTelegramChatIdBody telegramUsername(String telegramUsername) {
    
    this.telegramUsername = telegramUsername;
    return this;
  }

   /**
   * Get telegramUsername
   * @return telegramUsername
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getTelegramUsername() {
    return telegramUsername;
  }


  public void setTelegramUsername(String telegramUsername) {
    this.telegramUsername = telegramUsername;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetTelegramChatIdBody getTelegramChatIdBody = (GetTelegramChatIdBody) o;
    return Objects.equals(this.telegramUsername, getTelegramChatIdBody.telegramUsername);
  }

  @Override
  public int hashCode() {
    return Objects.hash(telegramUsername);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetTelegramChatIdBody {\n");
    sb.append("    telegramUsername: ").append(toIndentedString(telegramUsername)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("telegram_username");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("telegram_username");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to GetTelegramChatIdBody
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (GetTelegramChatIdBody.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in GetTelegramChatIdBody is not found in the empty JSON string", GetTelegramChatIdBody.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!GetTelegramChatIdBody.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GetTelegramChatIdBody` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : GetTelegramChatIdBody.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (jsonObj.get("telegram_username") != null && !jsonObj.get("telegram_username").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `telegram_username` to be a primitive type in the JSON string but got `%s`", jsonObj.get("telegram_username").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetTelegramChatIdBody.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetTelegramChatIdBody' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetTelegramChatIdBody> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetTelegramChatIdBody.class));

       return (TypeAdapter<T>) new TypeAdapter<GetTelegramChatIdBody>() {
           @Override
           public void write(JsonWriter out, GetTelegramChatIdBody value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetTelegramChatIdBody read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of GetTelegramChatIdBody given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of GetTelegramChatIdBody
  * @throws IOException if the JSON string is invalid with respect to GetTelegramChatIdBody
  */
  public static GetTelegramChatIdBody fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetTelegramChatIdBody.class);
  }

 /**
  * Convert an instance of GetTelegramChatIdBody to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

