openapi: 3.0.3
info:
  contact:
    email: ""
    name: ""
  description: ""
  license:
    name: ""
  title: notifier
  version: 0.3.2
servers:
- url: /
paths:
  /add_channel:
    post:
      deprecated: false
      description: |
        Add channel

        Add notification channel for user
      operationId: handle_add_channel
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddChannelBody'
        required: true
      responses:
        "200":
          description: Channel added successfully
      summary: Add channel
      tags:
      - crate
      x-content-type: application/json
      x-accepts: application/json
  /get_channels/{user_id}:
    get:
      deprecated: false
      description: |
        Get notification channels for user

        get all channels registered for user with given id
      operationId: handle_get_channels
      parameters:
      - deprecated: false
        description: User id to get notification channels for
        explode: false
        in: path
        name: user_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChannelsResponse'
          description: Notification channels retrieved successfully
      summary: Get notification channels for user
      tags:
      - crate
      x-accepts: application/json
  /get_telegram_chat_id/{username}:
    get:
      deprecated: false
      description: "Get the chat ID of a telegram username\n\nFirst call this endpoint,\
        \ then ask the user to send a message to the bot, then the chat id will be\
        \ returned\n"
      operationId: handle_get_telegram_chat_id
      parameters:
      - deprecated: false
        description: User id to get notification channels for
        explode: false
        in: path
        name: username
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
          description: Returns the chat ID
        "500":
          description: Could not look up username
      summary: Get the chat ID of a telegram username
      tags:
      - crate
      x-accepts: text/plain
  /notify:
    post:
      deprecated: false
      description: |
        Send notification

        send notification to user with given id on all channels registered for that user
      operationId: handle_notify
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NotifyBody'
        required: true
      responses:
        "200":
          description: Notification sent successfully
      summary: Send notification
      tags:
      - crate
      x-content-type: application/json
      x-accepts: application/json
  /remove_channel:
    post:
      deprecated: false
      description: |
        Remove channel

        Remove notification channel for user
      operationId: handle_remove_channel
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RemoveChannelBody'
        required: true
      responses:
        "200":
          description: Channel removed successfully
      summary: Remove channel
      tags:
      - crate
      x-content-type: application/json
      x-accepts: application/json
components:
  schemas:
    ChannelResponse:
      example:
        service_username: service_username
        service_id: service_id
      properties:
        service_username:
          type: string
        service_id:
          type: string
      required:
      - service_id
      - service_username
      type: object
    NotifyBody:
      example:
        user_id: user_id
        subject: subject
        message: message
      properties:
        message:
          type: string
        user_id:
          type: string
        subject:
          type: string
      required:
      - message
      - subject
      - user_id
      type: object
    AddChannelBody:
      example:
        user_id: user_id
        service_username: service_username
        service_id: service_id
      properties:
        user_id:
          type: string
        service_id:
          type: string
        service_username:
          type: string
      required:
      - service_id
      - service_username
      - user_id
      type: object
    ChannelsResponse:
      example:
        channels:
        - service_username: service_username
          service_id: service_id
        - service_username: service_username
          service_id: service_id
        user_id: user_id
      properties:
        channels:
          items:
            $ref: '#/components/schemas/ChannelResponse'
          type: array
        user_id:
          type: string
      required:
      - channels
      - user_id
      type: object
    RemoveChannelBody:
      example:
        user_id: user_id
        service_id: service_id
      properties:
        service_id:
          type: string
        user_id:
          type: string
      required:
      - service_id
      - user_id
      type: object

